// Integration tests for review-noise exclusion in the diff layer. Generated or
// oversized files (a regenerated ABI, a lockfile) must be subtracted from the
// review diff so they can't bloat the page or crash the renderer, and so the
// agent isn't sent chasing coverage it can't usefully narrate. Run with: npm test
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { chmodSync, mkdtempSync, writeFileSync, rmSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import {
  excludedReviewFiles,
  getDiff,
  noiseFiles,
  reviewChangeFingerprint,
  stagedWorktreeDivergentFiles,
} from '../dist/git.js';
import { parseUnifiedDiff } from '../dist/diff.js';

function repo() {
  const d = mkdtempSync(join(tmpdir(), 'ds-noise-'));
  const g = (args) => execFileSync('git', args, { cwd: d });
  g(['init', '-q']);
  g(['config', 'user.email', 't@e.st']);
  g(['config', 'user.name', 'T']);
  writeFileSync(join(d, 'seed.txt'), 'seed\n');
  g(['add', '.']);
  g(['commit', '-qm', 'init']);
  return { d, g };
}

test('a huge file is excluded by size; real code stays', () => {
  const { d, g } = repo();
  try {
    // A regenerated artifact: 2000 changed lines, over the 1500 threshold.
    writeFileSync(join(d, 'generated.txt'), Array.from({ length: 2000 }, (_, i) => `row ${i}`).join('\n') + '\n');
    writeFileSync(join(d, 'real.sol'), 'contract A {}\n');
    g(['add', '.']);

    assert.deepEqual(noiseFiles(d, 'HEAD'), ['generated.txt']);
    assert.deepEqual(excludedReviewFiles(d, 'HEAD'), [
      {
        path: 'generated.txt',
        reason: 'large-diff',
        addedLines: 2000,
        removedLines: 0,
        changedLines: 2000,
      },
    ]);
    const files = parseUnifiedDiff(getDiff(d, 'HEAD')).map((f) => f.newPath);
    assert.ok(files.includes('real.sol'), 'real code stays in the diff');
    assert.ok(!files.includes('generated.txt'), 'oversized file is excluded');
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('a small generated-by-path file (abis/) is excluded even when tiny', () => {
  const { d, g } = repo();
  try {
    mkdirSync(join(d, 'abis'));
    writeFileSync(join(d, 'abis', 'token.json'), '[{"a":1}]\n'); // tiny, but generated by path
    writeFileSync(join(d, 'real.ts'), 'export const x = 1;\n');
    g(['add', '.']);

    assert.deepEqual(noiseFiles(d, 'HEAD'), ['abis/token.json']);
    assert.deepEqual(excludedReviewFiles(d, 'HEAD'), [
      {
        path: 'abis/token.json',
        reason: 'generated-path',
        addedLines: 1,
        removedLines: 0,
        changedLines: 1,
      },
    ]);
    const files = parseUnifiedDiff(getDiff(d, 'HEAD')).map((f) => f.newPath);
    assert.ok(files.includes('real.ts'));
    assert.ok(!files.includes('abis/token.json'));
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('a small ordinary change is never excluded', () => {
  const { d, g } = repo();
  try {
    writeFileSync(join(d, 'small.txt'), Array.from({ length: 50 }, (_, i) => `line ${i}`).join('\n') + '\n');
    g(['add', '.']);
    assert.deepEqual(noiseFiles(d, 'HEAD'), []);
    assert.ok(parseUnifiedDiff(getDiff(d, 'HEAD')).map((f) => f.newPath).includes('small.txt'));
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('untracked ordinary files appear in the working-tree diff', () => {
  const { d } = repo();
  try {
    writeFileSync(join(d, 'new-note.md'), 'one\nsecond\n');

    const files = parseUnifiedDiff(getDiff(d, 'HEAD'));
    assert.equal(files.length, 1);
    assert.equal(files[0].status, 'added');
    assert.equal(files[0].newPath, 'new-note.md');
    assert.deepEqual(files[0].hunks[0].lines.filter((l) => l.type === 'add').map((l) => l.content), [
      'one',
      'second',
    ]);
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('untracked review-noise files are still excluded', () => {
  const { d } = repo();
  try {
    mkdirSync(join(d, 'abis'));
    writeFileSync(join(d, 'abis', 'token.json'), '[{"a":1}]\n');
    writeFileSync(join(d, 'useful.ts'), 'export const useful = true;\n');

    assert.deepEqual(noiseFiles(d, 'HEAD'), ['abis/token.json']);
    const files = parseUnifiedDiff(getDiff(d, 'HEAD')).map((f) => f.newPath);
    assert.deepEqual(files, ['useful.ts']);
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('diffStory review state never appears in the reviewed diff', () => {
  const { d } = repo();
  try {
    mkdirSync(join(d, '.diffstory'));
    writeFileSync(join(d, '.diffstory', 'review-state.json'), '{"version":1}\n');
    writeFileSync(join(d, 'useful.ts'), 'export const useful = true;\n');
    const files = parseUnifiedDiff(getDiff(d, 'HEAD')).map((f) => f.newPath);
    assert.deepEqual(files, ['useful.ts']);
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('ordinary binary and mode-only changes are explicit exclusions', () => {
  const { d, g } = repo();
  try {
    writeFileSync(join(d, 'image.bin'), Buffer.from([0, 1, 2, 3]));
    chmodSync(join(d, 'seed.txt'), 0o755);
    assert.deepEqual(excludedReviewFiles(d, 'HEAD'), [
      {
        path: 'image.bin', reason: 'binary',
        addedLines: null, removedLines: 0, changedLines: null,
      },
      {
        path: 'seed.txt', reason: 'metadata-only',
        addedLines: 0, removedLines: 0, changedLines: 0,
      },
    ]);
    assert.equal(parseUnifiedDiff(getDiff(d, 'HEAD')).length, 0);
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('complete-change fingerprint tracks excluded and untracked bytes without rendering them', () => {
  const { d } = repo();
  try {
    mkdirSync(join(d, 'dist'));
    writeFileSync(join(d, 'dist', 'bundle.js'), 'generated one\n');
    writeFileSync(join(d, 'asset.bin'), Buffer.from([0, 1, 2]));
    const first = reviewChangeFingerprint(d, 'HEAD');
    assert.equal(getDiff(d, 'HEAD'), '', 'both files stay outside the bounded renderer');

    writeFileSync(join(d, 'dist', 'bundle.js'), 'generated two\n');
    const generatedChanged = reviewChangeFingerprint(d, 'HEAD');
    assert.notEqual(generatedChanged, first);

    writeFileSync(join(d, 'asset.bin'), Buffer.from([0, 1, 3]));
    assert.notEqual(reviewChangeFingerprint(d, 'HEAD'), generatedChanged);
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('an MM file restored to the base still exposes its staged change', () => {
  const { d, g } = repo();
  try {
    writeFileSync(join(d, 'seed.txt'), 'staged value\n');
    g(['add', 'seed.txt']);
    writeFileSync(join(d, 'seed.txt'), 'seed\n');

    assert.match(String(g(['status', '--short', 'seed.txt'])), /^MM seed\.txt/m);
    assert.deepEqual(stagedWorktreeDivergentFiles(d, 'HEAD'), ['seed.txt']);

    const files = parseUnifiedDiff(getDiff(d, 'HEAD'));
    assert.equal(files.length, 1);
    assert.equal(files[0].newPath, 'seed.txt');
    assert.deepEqual(files[0].hunks[0].lines.filter((line) => line.type === 'add').map((line) => line.content), [
      'staged value',
    ]);
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('a staged deletion restored as untracked is one explicit divergent review path', () => {
  const { d, g } = repo();
  try {
    g(['rm', '--cached', 'seed.txt']);
    writeFileSync(join(d, 'seed.txt'), 'restored worktree value\n');

    assert.match(String(g(['status', '--short', 'seed.txt'])), /^D  seed\.txt\n\?\? seed\.txt$/m);
    assert.deepEqual(stagedWorktreeDivergentFiles(d, 'HEAD'), ['seed.txt']);

    const files = parseUnifiedDiff(getDiff(d, 'HEAD'));
    assert.deepEqual(
      files.map((file) => file.newPath || file.oldPath),
      ['seed.txt'],
      'the collision is gated as one path rather than rendered as duplicate delete/add files',
    );
    assert.equal(files[0].status, 'deleted', 'the bounded diff keeps the staged representation');
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('a staged deletion restored at an ignored path is still explicit divergence', () => {
  const { d, g } = repo();
  try {
    writeFileSync(join(d, '.gitignore'), 'seed.txt\n');
    g(['add', '.gitignore']);
    g(['commit', '-qm', 'ignore the tracked fixture']);
    g(['rm', '--cached', 'seed.txt']);
    writeFileSync(join(d, 'seed.txt'), 'restored but ignored worktree value\n');

    assert.match(String(g(['status', '--short', 'seed.txt'])), /^D  seed\.txt$/m);
    assert.deepEqual(stagedWorktreeDivergentFiles(d, 'HEAD'), ['seed.txt']);

    const files = parseUnifiedDiff(getDiff(d, 'HEAD'));
    assert.deepEqual(files.map((file) => file.newPath || file.oldPath), ['seed.txt']);
    assert.equal(files[0].status, 'deleted', 'one staged identity remains visible');
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('complete-change fingerprint independently tracks index identity', () => {
  const { d, g } = repo();
  try {
    writeFileSync(join(d, 'seed.txt'), 'first staged value\n');
    g(['add', 'seed.txt']);
    writeFileSync(join(d, 'seed.txt'), 'same worktree value\n');
    const rendered = getDiff(d, 'HEAD');
    const first = reviewChangeFingerprint(d, 'HEAD');

    writeFileSync(join(d, 'seed.txt'), 'second staged value\n');
    g(['add', 'seed.txt']);
    writeFileSync(join(d, 'seed.txt'), 'same worktree value\n');
    const second = reviewChangeFingerprint(d, 'HEAD');

    assert.equal(getDiff(d, 'HEAD'), rendered, 'aggregate rendered bytes remain unchanged');
    assert.notEqual(second, first, 'restaging different bytes invalidates exact-change identity');
    assert.deepEqual(stagedWorktreeDivergentFiles(d, 'HEAD'), ['seed.txt']);
    assert.deepEqual(stagedWorktreeDivergentFiles(d, 'HEAD', 'HEAD'), []);
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('committed branch content plus an unstaged edit is not mislabeled as staged divergence', () => {
  const { d, g } = repo();
  try {
    writeFileSync(join(d, 'seed.txt'), 'committed branch value\n');
    g(['add', 'seed.txt']);
    g(['commit', '-qm', 'branch change']);
    writeFileSync(join(d, 'seed.txt'), 'unstaged worktree value\n');

    assert.deepEqual(stagedWorktreeDivergentFiles(d, 'HEAD^'), []);
    assert.match(getDiff(d, 'HEAD^'), /unstaged worktree value/);
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('staged-only review noise remains an explicit exclusion when worktree matches the base', () => {
  const { d, g } = repo();
  try {
    const staged = Array.from({ length: 2000 }, (_, i) => `staged row ${i}`).join('\n') + '\n';
    writeFileSync(join(d, 'seed.txt'), staged);
    g(['add', 'seed.txt']);
    writeFileSync(join(d, 'seed.txt'), 'seed\n');

    assert.deepEqual(excludedReviewFiles(d, 'HEAD'), [
      {
        path: 'seed.txt',
        reason: 'large-diff',
        addedLines: 2000,
        removedLines: 1,
        changedLines: 2001,
      },
    ]);
    assert.equal(getDiff(d, 'HEAD'), '', 'the staged remainder is bounded by the same noise policy');
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});
