// Integration tests for review-noise exclusion in the diff layer. Generated or
// oversized files (a regenerated ABI, a lockfile) must be subtracted from the
// review diff so they can't bloat the page or crash the renderer, and so the
// agent isn't sent chasing coverage it can't usefully narrate. Run with: npm test
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, rmSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { getDiff, noiseFiles } from '../dist/git.js';
import { parseUnifiedDiff } from '../dist/diff.js';

function repo() {
  const d = mkdtempSync(join(tmpdir(), 'ds-noise-'));
  const g = (args) => execFileSync('git', args, { cwd: d });
  g(['init', '-q']);
  g(['config', 'user.email', 't@e.st']);
  g(['config', 'user.name', 'T']);
  writeFileSync(join(d, 'seed.txt'), 'seed\n');
  g(['add', '.']);
  g(['commit', '-qm', 'init']);
  return { d, g };
}

test('a huge file is excluded by size; real code stays', () => {
  const { d, g } = repo();
  try {
    // A regenerated artifact: 2000 changed lines, over the 1500 threshold.
    writeFileSync(join(d, 'generated.txt'), Array.from({ length: 2000 }, (_, i) => `row ${i}`).join('\n') + '\n');
    writeFileSync(join(d, 'real.sol'), 'contract A {}\n');
    g(['add', '.']);

    assert.deepEqual(noiseFiles(d, 'HEAD'), ['generated.txt']);
    const files = parseUnifiedDiff(getDiff(d, 'HEAD')).map((f) => f.newPath);
    assert.ok(files.includes('real.sol'), 'real code stays in the diff');
    assert.ok(!files.includes('generated.txt'), 'oversized file is excluded');
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('a small generated-by-path file (abis/) is excluded even when tiny', () => {
  const { d, g } = repo();
  try {
    mkdirSync(join(d, 'abis'));
    writeFileSync(join(d, 'abis', 'token.json'), '[{"a":1}]\n'); // tiny, but generated by path
    writeFileSync(join(d, 'real.ts'), 'export const x = 1;\n');
    g(['add', '.']);

    assert.deepEqual(noiseFiles(d, 'HEAD'), ['abis/token.json']);
    const files = parseUnifiedDiff(getDiff(d, 'HEAD')).map((f) => f.newPath);
    assert.ok(files.includes('real.ts'));
    assert.ok(!files.includes('abis/token.json'));
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('a small ordinary change is never excluded', () => {
  const { d, g } = repo();
  try {
    writeFileSync(join(d, 'small.txt'), Array.from({ length: 50 }, (_, i) => `line ${i}`).join('\n') + '\n');
    g(['add', '.']);
    assert.deepEqual(noiseFiles(d, 'HEAD'), []);
    assert.ok(parseUnifiedDiff(getDiff(d, 'HEAD')).map((f) => f.newPath).includes('small.txt'));
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('untracked ordinary files appear in the working-tree diff', () => {
  const { d } = repo();
  try {
    writeFileSync(join(d, 'new-note.md'), 'one\nsecond\n');

    const files = parseUnifiedDiff(getDiff(d, 'HEAD'));
    assert.equal(files.length, 1);
    assert.equal(files[0].status, 'added');
    assert.equal(files[0].newPath, 'new-note.md');
    assert.deepEqual(files[0].hunks[0].lines.filter((l) => l.type === 'add').map((l) => l.content), [
      'one',
      'second',
    ]);
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});

test('untracked review-noise files are still excluded', () => {
  const { d } = repo();
  try {
    mkdirSync(join(d, 'abis'));
    writeFileSync(join(d, 'abis', 'token.json'), '[{"a":1}]\n');
    writeFileSync(join(d, 'useful.ts'), 'export const useful = true;\n');

    assert.deepEqual(noiseFiles(d, 'HEAD'), ['abis/token.json']);
    const files = parseUnifiedDiff(getDiff(d, 'HEAD')).map((f) => f.newPath);
    assert.deepEqual(files, ['useful.ts']);
  } finally {
    rmSync(d, { recursive: true, force: true });
  }
});
