#!/bin/sh
# diffStory installer — no npm-global headaches.
#
#   curl -fsSL https://raw.githubusercontent.com/naveedinno/diffStory/main/scripts/install.sh | sh
#
# Clones diffStory to ~/.diffstory and drops a launcher on your PATH that runs the
# CLI via `node` (so there is no executable-bit / symlink fragility). Re-run any
# time to update. Override locations with DIFFSTORY_HOME and DIFFSTORY_BIN.
set -eu

REPO_HTTPS="https://github.com/naveedinno/diffStory.git"
REPO_SSH="git@github.com:naveedinno/diffStory.git"
DS_HOME="${DIFFSTORY_HOME:-$HOME/.diffstory}"
SRC="$DS_HOME/src"
BIN_DIR="${DIFFSTORY_BIN:-$HOME/.local/bin}"

say()  { printf '%s\n' "$*"; }
die()  { printf 'diffStory install error: %s\n' "$*" >&2; exit 1; }

command -v git  >/dev/null 2>&1 || die "git is required."
command -v node >/dev/null 2>&1 || die "Node.js >= 20 is required — see https://nodejs.org"
NODE_MAJOR=$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)
[ "$NODE_MAJOR" -ge 20 ] || die "Node.js >= 20 required (you have $(node -v 2>/dev/null))."

# Use SSH when it can reach the repo (needed while the repo is private); else HTTPS.
REPO="$REPO_HTTPS"
if GIT_SSH_COMMAND='ssh -o BatchMode=yes -o ConnectTimeout=5' git ls-remote "$REPO_SSH" >/dev/null 2>&1; then
  REPO="$REPO_SSH"
fi

say "› Fetching diffStory ($REPO)"
if [ -d "$SRC/.git" ]; then
  git -C "$SRC" remote set-url origin "$REPO"
  git -C "$SRC" fetch -q --depth 1 origin main
  git -C "$SRC" reset -q --hard origin/main
else
  mkdir -p "$DS_HOME"
  rm -rf "$SRC"
  git clone -q --depth 1 "$REPO" "$SRC"
fi

[ -f "$SRC/dist/cli.js" ] || die "build output missing at $SRC/dist/cli.js"

mkdir -p "$BIN_DIR"
LAUNCHER="$BIN_DIR/diffstory"
cat > "$LAUNCHER" <<EOF
#!/bin/sh
# diffStory launcher (generated by install.sh)
exec node "$SRC/dist/cli.js" "\$@"
EOF
chmod +x "$LAUNCHER"

say "› Installed launcher: $LAUNCHER"
VERSION=$(node "$SRC/dist/cli.js" --version 2>/dev/null || true)
[ -n "$VERSION" ] && say "› $VERSION"

# Ensure BIN_DIR is on PATH (bash, zsh, fish).
case ":${PATH}:" in
  *":$BIN_DIR:"*)
    say ""
    say "✓ Done. Try:  diffstory help"
    ;;
  *)
    LINE="export PATH=\"$BIN_DIR:\$PATH\""
    for rc in "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.profile"; do
      [ -e "$rc" ] || continue
      grep -qs "DIFFSTORY_BIN_PATH" "$rc" || printf '\n# DIFFSTORY_BIN_PATH\n%s\n' "$LINE" >> "$rc"
    done
    if [ -d "$HOME/.config/fish" ] || command -v fish >/dev/null 2>&1; then
      FISH="$HOME/.config/fish/config.fish"
      mkdir -p "$HOME/.config/fish"
      grep -qs "DIFFSTORY_BIN_PATH" "$FISH" 2>/dev/null || printf '\n# DIFFSTORY_BIN_PATH\nfish_add_path %s\n' "$BIN_DIR" >> "$FISH"
    fi
    say ""
    say "✓ Done. Added $BIN_DIR to your PATH."
    say "  Open a new terminal (or reload your shell), then:  diffstory help"
    ;;
esac
